using System.Collections.Generic;
using UnityEngine;

//======================================================================
// InGameLogger
// 実機（Android等）上で画面最前面にログを表示するデバッグユーティリティ
//======================================================================
public class InGameLogger : MonoBehaviour
{
	private Queue<string> _logs = new Queue<string>();
	private const int MaxLogs = 15;
	private bool _isVisible = true;

	//======================================================================
	// AutoInitialize
	// 26/08/14 10:45 ※JST
	//
	// [機能詳細]
	// 1. シーンロード完了時に自動的に呼び出されるエントリーポイント。
	// 2. シーン内に InGameLogger インスタンスが存在しない場合、自動生成する。
	// 3. 生成したオブジェクトを DontDestroyOnLoad に登録して常駐させる。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
	private static void AutoInitialize()
	{
		if (FindFirstObjectByType<InGameLogger>() != null)
		{
			Debug.Log("[InGameLogger] シーン上に既にインスタンスが存在するため、自動生成をスキップします。");
			return;
		}

		Debug.Log("[InGameLogger] 実機ログ表示用オブジェクトを自動生成します。");
		GameObject loggerObj = new GameObject("InGameLogger_AutoGenerated");
		loggerObj.AddComponent<InGameLogger>();
		DontDestroyOnLoad(loggerObj);
	}

	//======================================================================
	// Awake
	// 26/08/14 10:45 ※JST
	//
	// [機能詳細]
	// 1. インスタンスの重複チェックを行い、複数存在する場合は自身を破棄する。
	// 2. 唯一のインスタンスとして DontDestroyOnLoad を適用する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void Awake()
	{
		InGameLogger[] instanceList = FindObjectsByType<InGameLogger>(FindObjectsSortMode.None);
		if (instanceList.Length > 1)
		{
			Debug.Log("[InGameLogger] 重複したインスタンスを破棄します。");
			Destroy(gameObject);
			return;
		}

		DontDestroyOnLoad(gameObject);
	}

	//======================================================================
	// OnEnable
	// 26/08/14 10:45 ※JST
	//
	// [機能詳細]
	// 1. Unityのログ受信用コールバックイベントを登録する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void OnEnable()
	{
		Application.logMessageReceived += OnLogReceived;
		Debug.Log("[InGameLogger] ログ受信イベントを登録しました。");
	}

	//======================================================================
	// OnDisable
	// 26/08/14 10:45 ※JST
	//
	// [機能詳細]
	// 1. Unityのログ受信用コールバックイベントの登録を解除する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void OnDisable()
	{
		Application.logMessageReceived -= OnLogReceived;
	}

	private string _lastLogMessage = "";
	private int _sameLogCount = 1;
	private bool _isPaused = false;

	//======================================================================
	// OnLogReceived
	// 26/08/14 11:10 ※JST
	//
	// [機能詳細]
	// 1. 一時停止フラグ(_isPaused)が有効な場合、新規ログの蓄積をスキップする。
	// 2. 直前と同一のログ文字列を受信した場合、新規追加せず重複カウントをインクリメントする。
	// 3. 受信ログの種別に応じてリッチテキスト用カラーコードを設定する。
	// 4. 整形したログ文字列を内部キューへ追加し、上限数を超えた場合は最古のログを破棄する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    condition: ログメッセージ文字列
	//    stackTrace: コールスタック情報
	//    type: ログ種別 (LogType)
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void OnLogReceived(string condition, string stackTrace, LogType type)
	{
		if (_isPaused)
		{
			return;
		}

		if (condition == _lastLogMessage && _logs.Count > 0)
		{
			_sameLogCount++;
			return;
		}

		_lastLogMessage = condition;
		_sameLogCount = 1;

		string colorCode = type switch
		{
			LogType.Error => "#FF5555",
			LogType.Exception => "#FF5555",
			LogType.Warning => "#FFFF55",
			_ => "#FFFFFF"
		};

		string formattedLog = $"<color={colorCode}>[{type}] {condition}</color>";
		if ((type == LogType.Exception || type == LogType.Error) && !string.IsNullOrEmpty(stackTrace))
		{
			string[] traceLines = stackTrace.Split('\n');
			if (traceLines.Length > 0)
			{
				formattedLog += $"\n<color=#FF7777>  --> {traceLines[0]}</color>";
			}
		}

		_logs.Enqueue(formattedLog);
		while (_logs.Count > MaxLogs)
		{
			_logs.Dequeue();
		}
	}

	//======================================================================
	// OnGUI
	// 26/08/14 10:45 ※JST
	//
	// [機能詳細]
	// 1. 画面上に表示切り替えボタンを描画する。
	// 2. 表示フラグが有効な場合、画面上部にログ描画用ボックスを表示する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void OnGUI()
	{
		// 切り替えボタン描画サブ関数の呼び出し
		DrawToggleButton();

		if (!_isVisible)
		{
			return;
		}

		// ログテキスト領域描画サブ関数の呼び出し
		DrawLogBox();
	}

	private GUIStyle _cachedButtonStyle = null;

	//======================================================================
	// DrawToggleButton
	// 26/08/14 11:25 ※JST
	//
	// [機能詳細]
	// 1. 画面右上部にログ表示切替(LOG: ON/OFF)および一時停止切替(PAUSE/RUN)ボタンを描画する。
	// 2. GUIStyle をキャッシュ化し、毎フレームの動的生成によるエディタアサーションを防止する。
	// 3. 各ボタンの押下時に表示フラグ(_isVisible)および一時停止フラグ(_isPaused)を反転させる。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void DrawToggleButton()
	{
		float buttonWidth = Screen.width * 0.2f;
		float buttonHeight = Screen.height * 0.06f;

		if (_cachedButtonStyle == null)
		{
			_cachedButtonStyle = new GUIStyle(GUI.skin.button);
		}
		_cachedButtonStyle.fontSize = Mathf.Clamp(Mathf.RoundToInt(Screen.height * 0.018f), 14, 32);

		// 1. LOG 表示 / 非表示 切替ボタン
		Rect visibleBtnRect = new Rect(Screen.width - buttonWidth - 20f, 20f, buttonWidth, buttonHeight);
		string visibleLabel = _isVisible ? "LOG: ON" : "LOG: OFF";
		if (GUI.Button(visibleBtnRect, visibleLabel, _cachedButtonStyle))
		{
			_isVisible = !_isVisible;
		}

		// 2. PAUSE / RUN 一時停止切替ボタン
		Rect pauseBtnRect = new Rect(Screen.width - (buttonWidth * 2f) - 30f, 20f, buttonWidth, buttonHeight);
		string pauseLabel = _isPaused ? "RUN" : "PAUSE";
		if (GUI.Button(pauseBtnRect, pauseLabel, _cachedButtonStyle))
		{
			_isPaused = !_isPaused;
		}
	}

	private GUIStyle _cachedBoxStyle = null;

	//======================================================================
	// DrawLogBox
	// 26/08/14 11:26 ※JST
	//
	// [機能詳細]
	// 1. 画面上部にログ表示用の背景ボックスおよび集約・整形済みログテキストを出力する。
	// 2. GUIStyle をキャッシュ化し、毎フレームの動的生成によるエディタアサーションを防止する。
	// 3. 直前と同内容のログが連続で発生している場合、末尾に重複カウント数を付与して表示する。
	//
	//----------------------------------------------------------------------
	// [引数]
	//    なし
	//
	// [戻り値]
	//    {void}
	//======================================================================
	private void DrawLogBox()
	{
		float boxWidth = Screen.width - 40f;
		float boxHeight = Screen.height * 0.45f;
		float topMargin = Screen.height * 0.08f;
		Rect boxRect = new Rect(20f, topMargin, boxWidth, boxHeight);

		if (_cachedBoxStyle == null)
		{
			_cachedBoxStyle = new GUIStyle(GUI.skin.box)
			{
				alignment = TextAnchor.UpperLeft,
				wordWrap = true,
				richText = true
			};
		}
		_cachedBoxStyle.fontSize = Mathf.Clamp(Mathf.RoundToInt(Screen.height * 0.015f), 12, 28);

		List<string> displayLogs = new List<string>(_logs);
		if (_sameLogCount > 1 && displayLogs.Count > 0)
		{
			int lastIndex = displayLogs.Count - 1;
			displayLogs[lastIndex] = $"{displayLogs[lastIndex]} <color=#AAAAAA>(x{_sameLogCount})</color>";
		}

		string allLogsText = string.Join("\n", displayLogs);
		GUI.Box(boxRect, allLogsText, _cachedBoxStyle);
	}}